"""extra_document

Revision ID: 09cf9d60fd13
Revises: bc14c17863ee
Create Date: 2026-04-29 14:01:12.255758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cf9d60fd13'
down_revision: Union[str, Sequence[str], None] = 'bc14c17863ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extra_documents', sa.Column('website_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'extra_documents', 'websites', ['website_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extra_documents', type_='foreignkey')
    op.drop_column('extra_documents', 'website_id')
    # ### end Alembic commands ###
