"""index

Revision ID: 1ad5000257e6
Revises: 45d15e5ede56
Create Date: 2026-05-03 15:13:25.388621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ad5000257e6"
down_revision: Union[str, Sequence[str], None] = "45d15e5ede56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("attachments_user_id_fkey"), "attachments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("attachments_extra_document_id_fkey"), "attachments", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "attachments", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None,
        "attachments",
        "extra_documents",
        ["extra_document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("documents_website_id_fkey"), "documents", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "documents", "websites", ["website_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("embeddings_extra_document_id_fkey"), "embeddings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("embeddings_document_id_fkey"), "embeddings", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "embeddings", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "embeddings",
        "extra_documents",
        ["extra_document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("extra_documents_company_id_fkey"), "extra_documents", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("extra_documents_website_id_fkey"), "extra_documents", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "extra_documents", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "extra_documents", "websites", ["website_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("settings_company_id_fkey"), "settings", type_="foreignkey")
    op.create_foreign_key(
        None, "settings", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("users_company_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(
        None, "users", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint(None, "website_pages", ["website_id", "url"])
    op.drop_constraint(
        op.f("website_pages_website_id_fkey"), "website_pages", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "website_pages", "websites", ["website_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("websites_company_id_fkey"), "websites", type_="foreignkey")
    op.create_foreign_key(
        None, "websites", "companies", ["company_id"], ["id"], ondelete="CASCADE"
    )
    # index
    op.execute(
        "CREATE INDEX idx_embeddings_vector ON embeddings USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "websites", type_="foreignkey")
    op.create_foreign_key(
        op.f("websites_company_id_fkey"),
        "websites",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "website_pages", type_="foreignkey")
    op.create_foreign_key(
        op.f("website_pages_website_id_fkey"),
        "website_pages",
        "websites",
        ["website_id"],
        ["id"],
    )
    op.drop_constraint(None, "website_pages", type_="unique")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_company_id_fkey"), "users", "companies", ["company_id"], ["id"]
    )
    op.drop_constraint(None, "settings", type_="foreignkey")
    op.create_foreign_key(
        op.f("settings_company_id_fkey"),
        "settings",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "extra_documents", type_="foreignkey")
    op.drop_constraint(None, "extra_documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("extra_documents_website_id_fkey"),
        "extra_documents",
        "websites",
        ["website_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("extra_documents_company_id_fkey"),
        "extra_documents",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(None, "embeddings", type_="foreignkey")
    op.drop_constraint(None, "embeddings", type_="foreignkey")
    op.create_foreign_key(
        op.f("embeddings_document_id_fkey"),
        "embeddings",
        "documents",
        ["document_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("embeddings_extra_document_id_fkey"),
        "embeddings",
        "extra_documents",
        ["extra_document_id"],
        ["id"],
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("documents_website_id_fkey"),
        "documents",
        "websites",
        ["website_id"],
        ["id"],
    )
    op.drop_constraint(None, "attachments", type_="foreignkey")
    op.drop_constraint(None, "attachments", type_="foreignkey")
    op.create_foreign_key(
        op.f("attachments_extra_document_id_fkey"),
        "attachments",
        "extra_documents",
        ["extra_document_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("attachments_user_id_fkey"), "attachments", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
