"""update user role and company use date

Revision ID: 2a719698d131
Revises: 7e34b3d80b73
Create Date: 2026-04-19 07:25:59.613052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a719698d131'
down_revision: Union[str, Sequence[str], None] = '7e34b3d80b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('expired_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_column('companies', 'expired_at')
    op.drop_column('companies', 'started_at')
    # ### end Alembic commands ###
