"""website

Revision ID: b954e1c9dae1
Revises: 09cf9d60fd13
Create Date: 2026-05-01 14:51:21.970171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b954e1c9dae1'
down_revision: Union[str, Sequence[str], None] = '09cf9d60fd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('websites', sa.Column('ingest_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'ingest_status')
    op.drop_column('websites', 'status')
    # ### end Alembic commands ###
