"""add fields

Revision ID: bc14c17863ee
Revises: 2a719698d131
Create Date: 2026-04-20 08:57:06.463087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc14c17863ee'
down_revision: Union[str, Sequence[str], None] = '2a719698d131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('attachments', sa.Column('status', sa.String(length=50), nullable=True))
    op.alter_column('attachments', 'extra_document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('attachments', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('idx_attachments_extra_document_id', 'attachments', ['extra_document_id'], unique=False)
    op.create_index('idx_attachments_user_id', 'attachments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('hash_string', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hash_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_type')
    op.drop_column('users', 'hash_string')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_index('idx_attachments_user_id', table_name='attachments')
    op.drop_index('idx_attachments_extra_document_id', table_name='attachments')
    op.alter_column('attachments', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('attachments', 'extra_document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('attachments', 'status')
    op.drop_column('attachments', 'user_id')
    # ### end Alembic commands ###
